### ISSUE TITLE
Suggestions for improved sorting

### ISSUE THREAD

**Issue by OpitZle** [bousqi/osmmaps_dl#1]
I have two sugestions to improve sorting along the first column (Type/Area), so that all files belonging to one country group together in the GUI list:
1. In file "asset_tw_item.py" 
replace:
        # extended sorting on type
        if column == COL_TYPE:
            if self.asset.type.lower() == other_item.asset.type.lower():
                return self.asset.name.lower() < other_item.asset.name.lower()
            return self.asset.type.lower() < other_item.asset.type.lower()
by:
        # extended sorting on type
        if column == COL_TYPE:
            if self.asset.area.lower() == other_item.asset.area.lower():
                return self.asset.name.lower() < other_item.asset.name.lower()
            return self.asset.area.lower() < other_item.asset.area.lower()

2. In file "constants.py"
replace:
FILE_PREFIXES = ["Hillshade", "Slope"]
by:
FILE_PREFIXES = ["Hillshade", "Slope", "Weather", "Heightmap"]

And one typo:
3. Again in file "asset_tw_item.py"
remove duplicate lines:
        if column == COL_DATE:
            return self.asset.remote_date

**Comment by bousqi** [comment]
Oh nice to realize that some other people are taking advantage of my tool 😁
First of all thanks for your contribution. I'll review the impact of your proposals and eventually merge them.
In fact sorting was already expected to group per country, but I'll double check that point.

**Comment by bousqi** [comment]
👍 approved !

I'll push an update

**Comment by bousqi** [comment]
fixed on [v1.0.10](https://github.com/bousqi/osm-ad/tree/v1.0.10)
